//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Releaser.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllUser
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string FULLNAME { get; set; }
        public string FULLNAME2 { get; set; }
        public string TYPE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> EMPID { get; set; }
        public Nullable<int> CONTACT_KEY { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public int IsDisabled { get; set; }
    }
}
