//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Releaser.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_METADATA
    {
        public int DOC_METADATA_ID { get; set; }
        public int DOC_ID { get; set; }
        public string TITLE { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<System.DateTime> DOC_UPD_DATE { get; set; }
        public string DOC_MIME_TYPE { get; set; }
        public string DOC_EXTENSION { get; set; }
        public string APP_NAME { get; set; }
        public string ins_user { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public string upd_user { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
        public Nullable<System.DateTime> DocumentDeleted { get; set; }
        public string docTypeCode { get; set; }
        public Nullable<int> repository_type { get; set; }
        public string repository_id { get; set; }
        public Nullable<int> version_count { get; set; }
        public Nullable<int> ItemFileId { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public Nullable<bool> IsFinal { get; set; }
        public string Notes { get; set; }
    
        public virtual DOC DOC { get; set; }
        public virtual ItemFile ItemFile { get; set; }
    }
}
