//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Releaser.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemStatu()
        {
            this.ItemStatusNextValids = new HashSet<ItemStatusNextValid>();
            this.ItemStatusNextValids1 = new HashSet<ItemStatusNextValid>();
            this.RDIItems = new HashSet<RDIItem>();
        }
    
        public int ItemStatusId { get; set; }
        public string ItemStatus { get; set; }
        public string ins_user { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public string upd_user { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
        public int ApplicationId { get; set; }
        public int SortOrder { get; set; }
        public string StatusDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemStatusNextValid> ItemStatusNextValids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemStatusNextValid> ItemStatusNextValids1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDIItem> RDIItems { get; set; }
    }
}
