//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Releaser.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDIItemHistory
    {
        public int RDIItemHistoryId { get; set; }
        public int RDIItemId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public Nullable<int> ParentRDIItemId { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string UpdateNote { get; set; }
        public string ins_user { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public string upd_user { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
        public Nullable<int> HoursEstimated { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> PROJECT_NO { get; set; }
        public Nullable<int> PHASE { get; set; }
        public Nullable<int> TASK { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FeatureBranch { get; set; }
        public string ChangedDescription { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> RecurringRDIItemId { get; set; }
        public Nullable<System.DateTime> LastCreated { get; set; }
        public Nullable<System.DateTime> NextCreation { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public string ScheduleFieldName { get; set; }
        public string ScheduleCode { get; set; }
        public string ScheduleDetail { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public Nullable<System.DateTime> ScheduleEndDate { get; set; }
        public Nullable<bool> SchedulePause { get; set; }
    
        public virtual RDIItem RDIItem { get; set; }
    }
}
