//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Releaser.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDIItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RDIItem()
        {
            this.ItemFiles = new HashSet<ItemFile>();
            this.ItemSubscribers = new HashSet<ItemSubscriber>();
            this.RDIItemHistories = new HashSet<RDIItemHistory>();
            this.RDIItemPageTitles = new HashSet<RDIItemPageTitle>();
            this.RDIItemTags = new HashSet<RDIItemTag>();
        }
    
        public int RDIItemId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> PROJECT_NO { get; set; }
        public Nullable<int> PHASE { get; set; }
        public Nullable<int> TASK { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public string ins_user { get; set; }
        public Nullable<System.DateTime> ins_date { get; set; }
        public string upd_user { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
        public Nullable<int> ParentRDIItemId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string Comments { get; set; }
        public Nullable<int> HoursEstimated { get; set; }
        public string FeatureBranch { get; set; }
        public string ChangedDescription { get; set; }
        public Nullable<int> RecurringRDIItemId { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public bool IsRecurring { get; set; }
        public Nullable<System.DateTime> LastCreated { get; set; }
        public Nullable<System.DateTime> NextCreation { get; set; }
        public string ScheduleFieldName { get; set; }
        public string ScheduleCode { get; set; }
        public string ScheduleDetail { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public Nullable<System.DateTime> ScheduleEndDate { get; set; }
        public Nullable<bool> SchedulePause { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemFile> ItemFiles { get; set; }
        public virtual ItemPriority ItemPriority { get; set; }
        public virtual ItemStatu ItemStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSubscriber> ItemSubscribers { get; set; }
        public virtual ItemType ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDIItemHistory> RDIItemHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDIItemPageTitle> RDIItemPageTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDIItemTag> RDIItemTags { get; set; }
    }
}
